set define off;

INSERT INTO DEPARTMENT 	(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_HEAD) 	VALUES (	DEPARTMENT_ID_SEQ.nextval, 	'	Industrial Arts & Consumer Services	'	,	'	Friday Maryanne	'	);
INSERT INTO DEPARTMENT 	(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_HEAD) 	VALUES (	DEPARTMENT_ID_SEQ.nextval, 	'	Arts	'	,	'	Ashish Royal	'	);
INSERT INTO DEPARTMENT 	(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_HEAD) 	VALUES (	DEPARTMENT_ID_SEQ.nextval, 	'	Business	'	,	'	America Apollonia	'	);
INSERT INTO DEPARTMENT 	(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_HEAD) 	VALUES (	DEPARTMENT_ID_SEQ.nextval, 	'	Computers & Mathematics	'	,	'	Ada Lovelace	'	);
INSERT INTO DEPARTMENT 	(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_HEAD) 	VALUES (	DEPARTMENT_ID_SEQ.nextval, 	'	Law & Public Policy	'	,	'	Ainz Ooal Gown	'	);
INSERT INTO DEPARTMENT 	(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_HEAD) 	VALUES (	DEPARTMENT_ID_SEQ.nextval, 	'	Agriculture & Natural Resources	'	,	'	Varsha Kimberleigh	'	);
INSERT INTO DEPARTMENT 	(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_HEAD) 	VALUES (	DEPARTMENT_ID_SEQ.nextval, 	'	Communications & Journalism	'	,	'	Esmee Caprice	'	);
INSERT INTO DEPARTMENT 	(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_HEAD) 	VALUES (	DEPARTMENT_ID_SEQ.nextval, 	'	Engineering	'	,	'	Nikola Tesla	'	);
INSERT INTO DEPARTMENT 	(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_HEAD) 	VALUES (	DEPARTMENT_ID_SEQ.nextval, 	'	Social Science	'	,	'	Bria Woody	'	);
INSERT INTO DEPARTMENT 	(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_HEAD) 	VALUES (	DEPARTMENT_ID_SEQ.nextval, 	'	Health	'	,	'	Mridula Sully	'	);
INSERT INTO DEPARTMENT 	(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_HEAD) 	VALUES (	DEPARTMENT_ID_SEQ.nextval, 	'	Interdisciplinary	'	,	'	Luther Sima	'	);
INSERT INTO DEPARTMENT 	(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_HEAD) 	VALUES (	DEPARTMENT_ID_SEQ.nextval, 	'	Physical Sciences	'	,	'	Dr. Stone	'	);
INSERT INTO DEPARTMENT 	(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_HEAD) 	VALUES (	DEPARTMENT_ID_SEQ.nextval, 	'	Humanities & Liberal Arts	'	,	'	Warren Timoteo	'	);
INSERT INTO DEPARTMENT 	(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_HEAD) 	VALUES (	DEPARTMENT_ID_SEQ.nextval, 	'	Psychology & Social Work	'	,	'	Ted Ulisse	'	);
INSERT INTO DEPARTMENT 	(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_HEAD) 	VALUES (	DEPARTMENT_ID_SEQ.nextval, 	'	Biology & Life Science	'	,	'	Ardith Lacie	'	);
INSERT INTO DEPARTMENT 	(DEPARTMENT_ID, DEPARTMENT_NAME, DEPARTMENT_HEAD) 	VALUES (	DEPARTMENT_ID_SEQ.nextval, 	'	Education	'	,	'	Adelardo Josey	'	);
