-- drop DEMO tables from OracleXE (run twice)
DROP TABLE demo_customers;
DROP TABLE demo_order_items;
DROP TABLE demo_orders;
DROP TABLE demo_product_info;
DROP TABLE demo_states;
DROP TABLE demo_users;
DROP TABLE dept;
DROP TABLE emp;

-- Drop existing tables

DROP TABLE PROGRAMCOURSE;
DROP TABLE PREREQUISITE;
DROP TABLE COURSE;
DROP TABLE SECTION; 
DROP TABLE ENROLLMENT;
DROP TABLE PROGRAM;
DROP TABLE DEPARTMENT;
DROP TABLE STUDENT;

-- tables creation

CREATE TABLE department 
(
  DEPARTMENT_ID NUMBER(9,0) NOT NULL,
  DEPARTMENT_NAME VARCHAR2(20),  
  DEPARTMENT_HEAD VARCHAR2(20), 
  CAPACITY NUMBER(3,0),
    CONSTRAINT DEPARTMENT_PK  PRIMARY KEY (DEPARTMENT_ID)
);

CREATE TABLE PROGRAM 
(
  PROGRAM_ID NUMBER NOT NULL, 
  PROGRAM_NAME VARCHAR2(100), 
  NO_OF_TERMS NUMBER(2,0), 
  FEES NUMBER(9,2), 
  DEPARTMENT_ID NUMBER(9,0),
    CONSTRAINT PROGRAM_PK PRIMARY KEY (PROGRAM_ID), 
    CONSTRAINT DEPARTMENT_FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID)
);

CREATE TABLE STUDENT 
(
  STUDENT_ID NUMBER(9,0) NOT NULL,
  STUDENT_FIRST_NAME VARCHAR2(50) NOT NULL,
  STUDENT_MIDDLE_NAME VARCHAR2(50), 
  STUDENT_LAST_NAME VARCHAR2(71) NOT NULL, 
  TELEPHONE VARCHAR2(31) NOT NULL, 
  EMAIL VARCHAR2(256) NOT NULL, 
  ADDRESS VARCHAR2(100),
  PROVINCE VARCHAR2(40),
  COUNTRY VARCHAR2(60),
  IS_DOMESTIC NUMBER(1,0) NOT NULL,
  IDENTITY_NO VARCHAR2(20),
  SIN NUMBER(9,0),
  DOB DATE,
    CONSTRAINT STUDENT_PK PRIMARY KEY (STUDENT_ID)
);

CREATE TABLE ENROLLMENT 
(
  ENROLLMENT_ID NUMBER(9) NOT NULL,
  STUDENT_ID NUMBER(9) NOT NULL,
  PROGRAM_ID NUMBER(9),
  STATUS NUMBER(1,0),
  CURRENT_TERM NUMBER(2,0),
  ENROLL_DATE DATE,
  TOTAL_FEES NUMBER(9, 2),
    CONSTRAINT ENROLLMENT_PK PRIMARY KEY (ENROLLMENT_ID),
    CONSTRAINT STUDENT_FK FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    CONSTRAINT PROGRAM_ENROLL_FK FOREIGN KEY (PROGRAM_ID) REFERENCES PROGRAM(PROGRAM_ID)
);

CREATE TABLE COURSE 
(
  COURSE_ID NUMBER(9,0) NOT NULL,
  COURSE_NAME VARCHAR2(100),
  COURSE_CODE VARCHAR2(10),
  COURSE_DESC VARCHAR2(100),
  NO_CREDITS NUMBER(2,0),

  SECTION_ID NUMBER(9,0),
    CONSTRAINT COURSE_PK PRIMARY KEY (COURSE_ID)
);

CREATE TABLE SECTION 
(
  SECTION_ID NUMBER(9,0) NOT NULL,
  SECTION_TYPE VARCHAR2(20),
  PROFESSOR_NAME VARCHAR2(121),
  CAPACITY NUMBER(3,0),
  COURSE_ID NUMBER(9,0),
    CONSTRAINT SECTION_PK PRIMARY KEY (SECTION_ID),
    CONSTRAINT COURSE_FK FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID)
);

CREATE TABLE PREREQUISITE 
(
  PREREQ_COURSE NUMBER(9) NOT NULL,
  COURSE_ID NUMBER(9,0),
    CONSTRAINT PREREQUISITE_PK PRIMARY KEY (PREREQ_COURSE, COURSE_ID),
    CONSTRAINT COURSE_ID_FK FOREIGN KEY (COURSE_ID) REFERENCES COURSE (COURSE_ID)
);

CREATE TABLE PROGRAMCOURSE 
(
  PROGRAM_ID NUMBER(9),
  COURSE_ID NUMBER(9) CONSTRAINT COURSE_PC_FK REFERENCES COURSE(COURSE_ID),
    CONSTRAINT PROGRAMCOURSE_PK PRIMARY KEY (PROGRAM_ID, COURSE_ID),
    CONSTRAINT PROGRAM_PC_FK FOREIGN KEY (PROGRAM_ID) REFERENCES PROGRAM(PROGRAM_ID)
);







