create or replace TRIGGER delete_enrollment_trg
BEFORE DELETE ON ENROLLMENT
FOR EACH ROW
BEGIN
INSERT INTO ENROLLMENT_HISTORY VALUES(ENROLLMENTHISTORY_ID_SEQ.NEXTVAL, :OLD.ENROLLMENT_ID,
:OLD.STUDENT_ID, :OLD.PROGRAM_ID, :OLD.STATUS, :OLD.CURRENT_TERM, :OLD.ENROLL_DATE, :OLD.TOTAL_FEES,
'DELETE',SYSDATE );
END delete_enrollment_trg;