create or replace TRIGGER update_enrollment_trg
BEFORE UPDATE ON ENROLLMENT
FOR EACH ROW
BEGIN
INSERT INTO ENROLLMENT_HISTORY VALUES(ENROLLMENTHISTORY_ID_SEQ.NEXTVAL, :OLD.ENROLLMENT_ID,
:OLD.STUDENT_ID, :OLD.PROGRAM_ID, :OLD.STATUS, :OLD.CURRENT_TERM, :OLD.ENROLL_DATE, :OLD.TOTAL_FEES,
'UPDATE',SYSDATE );
END update_enrollment_trg;