-- drop Sequences in case that it will be needed

DROP SEQUENCE COURSE_ID_SEQ;
DROP SEQUENCE DEPARTMENT_ID_SEQ;
DROP SEQUENCE ENROLLMENT_ID_SEQ;
DROP SEQUENCE PROGRAM_ID_SEQ;
DROP SEQUENCE SECTION_ID_SEQ;
DROP SEQUENCE STUDENT_ID_SEQ;
